#!/bin/bash

pattern="--server-port +([0-9]+)"
address_opt="https://172.17.40.64:"

if  [[ "$@" =~ $pattern ]]
then 
	address_opt="$address_opt${BASH_REMATCH[1]}"
else
	address_opt="$address_opt""5683"
fi


python ai_controller.py  --address "$address_opt"  --use-occupancy --view-radius 50 $(echo $@ | sed 's/--server-port \+[[:digit:]]\+//')
